### ISSUE TITLE
not compatible with wp-graphQL > 0.8 v

### ISSUE THREAD

**Issue by zmn-aamir** [valu-digital/wp-graphql-offset-pagination#3]
can you update your plugin with latest plugin ?

**Comment by jasonbahl** [comment]
@zmn-aamir thanks for reporting 🙏.  

I'm working on a PR to get this updated. Should have something shortly.

**Comment by jasonbahl** [comment]
@zmn-aamir This was my fault in the core WPGraphQL plugin. I made some breaking changes that had further reaching affect than I had realized. 

I have a PR in to the core WPGraphQL (https://github.com/wp-graphql/wp-graphql/pull/1241), and will have a PR to this codebase in a minute too.

**Comment by jasonbahl** [comment]
WPGraphQL v0.8.3 PR here: https://github.com/wp-graphql/wp-graphql/pull/1242

**Comment by esamattis** [comment]
Merged support to master but it requires this to be released with the wp-graphql core:

https://github.com/wp-graphql/wp-graphql/pull/1245

I'll make a release once wp-graphql makes the release.

For now you can use the master from this repo and the develop branch from wp-graphql.

**Comment by yossisp** [comment]
I'm using [wpgraphql](https://github.com/wp-graphql/wp-graphql) version 1.0.5. This plugin doesn't seem to be working that is in the GraphQL IDE which built in into wordpress when I click on `posts.pageInfo` resolver in the graphql explorer I don't see `offsetPagination` option. Has this issue been resolved?
