### ISSUE TITLE
offsetPagination not show in woocommerce product type

### ISSUE THREAD

**Issue by AsunaxRan** [valu-digital/wp-graphql-offset-pagination#9]
offsetPagination show in other custom post type but not include product (woocommerce). 
Can you check this?
I'm using
- Wordpress: 5.7
- WooCommerce: 5.1.0
- WP GraphQL: 1.3.4
- WPGraphQL WooCommerce (WooGraphQL): 0.7.0
- WPGraphQL Offset Pagination: 0.2.0

**Comment by esamattis** [comment]
Duplicate #1
